Allow custom sampling rate and number of audio channels at separation time.
facebookresearch/demucs pull request #162
Opened 2021-02-23 22:35 UTC by jjburred

As a byproduct, the sampling rate is always passed to `utils.apply_model` in order for the random shifts and split segments to be calculated in seconds.

2021-02-24 13:29 UTC, adefossez requested changes
Hi Juanjo, thanks for the PR!

It is looking good as is, but I think the extra parameters to `separate` could be troubling, while the information should be bundled in the model, to avoid any possible inconsistency. `audio_channels` can already be recovered from the model as an attribute. Here, we could add `samplerate`, https://github.com/facebookresearch/demucs/blob/master/demucs/model.py#L76

It won't be used by anything in the model, only to be available at separation time. If you set the default value in the constructor of the Demucs class to 44100, it will also be automatically backfilled for already trained models (at this value).

2021-02-24 14:28 UTC, jjburred commented
ok, I'm about to commit a fix. Just to be sure about backwards compatibility: are all pre-trained (downloadable) models trained at 44100?

2021-02-24 16:17 UTC, jjburred commented
Here's the commit with the sampling rate embedded in the model. But note that this won't work with pre-trained models that were trained with sampling rates other than 44100.

2021-03-01 09:03 UTC, adefossez approved these changes

2021-03-01 09:04 UTC, adefossez commented
Awesome, thanks a lot!
All the pre-trained models I provide are for 44.1 kHz, and if someone did a different sample rate they probably had to hack their solutions around, so it is fine :)

2021-03-01 09:04 UTC, merged