avoid using mps for complex numbers
facebookresearch/demucs pull request #503
Opened 2023-05-30 18:57 UTC by HeLehm

This is kind of a dirty workaround but it does increase performance on mps devices.
As soon as PyTorch implements complex numbers for mps, this should be removed.

Issues: #435 and #432

2023-05-31 01:11 UTC, CarlGao4 approved these changes
Have you tested that whether it can be used on mps?

2023-05-31 08:19 UTC, HeLehm commented
Yes, I have and it does improve performance.

2023-05-31 14:37 UTC, adefossez approved these changes

2023-05-31 14:40 UTC, adefossez commented
Seems like the linter is not passing, this is mandatory for accepting the PR!
Also, it is best to update the docs/release.md file, e.g. as in https://github.com/facebookresearch/demucs/pull/501/files#diff-87479ac9ea16cec5ceafce00b3b049d7d5920cb663afae42901f20e7c4e6705d

2023-05-31 14:40 UTC, adefossez requested changes
Linter is failing, update the docs/release.md file ! otherwise all good :)

2023-05-31 15:12 UTC, CarlGao4 reviewed
These are the changes required by linter

2023-05-31 15:12 UTC, CarlGao4 commented on demucs/hdemucs.py
> +
Remove the empty spaces

2023-05-31 15:12 UTC, CarlGao4 commented on demucs/htdemucs.py
> +
Remove the empty spaces

2023-06-01 09:07 UTC, HeLehm commented
Thank you for your help! All requested changes are present in the last commit.

2023-06-01 10:13 UTC, CarlGao4 commented
I also have a suggestion:
Use `Fix #435 and fix #432` in your description so the issues will be automatically closed

2023-06-01 15:50 UTC, HeLehm commented
> I also have a suggestion:
> Use `Fix #435 and fix #432` in your description so the issues will be automatically closed

Like this?

2023-06-01 23:37 UTC, CarlGao4 commented
Yes! Now you can see that these issues are linked with this PR:
![image](https://github.com/facebookresearch/demucs/assets/57826826/95fa3134-8eb2-4c07-b186-d0714338c487)

2023-06-02 13:42 UTC, adefossez commented
perfect!

2023-06-02 13:42 UTC, merged

2023-06-03 01:02 UTC, CarlGao4 commented
> do you know what is the speed up?

What do you mean?

2023-06-03 07:55 UTC, remorses commented
How much faster is it on Mac now?

2023-06-03 10:59 UTC, HeLehm commented
Yes I did some test (code in https://github.com/HeLehm/demucs/blob/mps_speed_test/mps_speed_test.ipynb)

Results:

Testing mdx
CPU time: 67.53s, MPS time: 224.81s
Speedup: 0.30x

Testing htdemucs
CPU time: 52.90s, MPS time: 14.44s
Speedup: 3.66x

Testing htdemucs_ft
CPU time: 210.97s, MPS time: 49.38s
Speedup: 4.27x

Testing htdemucs_6s
CPU time: 50.26s, MPS time: 12.76s
Speedup: 3.94x

Testing hdemucs_mmi
CPU time: 21.59s, MPS time: 62.02s
Speedup: 0.35x

Testing mdx_extra
CPU time: 79.57s, MPS time: 210.56s
Speedup: 0.38x

I think It is weird that these mdx models take longer on mps than on cpu... This should be investigated.

2023-06-03 13:58 UTC, CarlGao4 commented
More precisely, v3 (hdemucs) models are slower on mps
Can you try timing the cpu part when separating on mps? And see whether the rest parts are slower

2023-06-06 14:26 UTC, HeLehm commented
> More precisely, v3 (hdemucs) models are slower on mps
> Can you try timing the cpu part when separating on mps? And see whether the rest parts are slower

Yes, will do. Sorry, I haven't found the time to to it yet. Will try next week.

2023-06-08 06:11 UTC, archive-r commented
Great! This gives me a 6x speedup on my mbp14.

2023-06-08 19:59 UTC, HeLehm commented
Ok I ran by tests more extensively by using this code:

```
def time_model(model_name, device, grad=False, n=1):
    model = pretrained.get_model(model_name)
    x = torch.randn(1, 2, 44100 * 30).to(device=device)  # 30 seconds of white noise for the test
    
    if grad:
        time = timeit.timeit(lambda: apply_model(model, x, device=device), number=n)
    else:
        with torch.no_grad():
            time = timeit.timeit(lambda: apply_model(model, x, device=device), number=n)

    del model
    del x
    gc.collect()

    time /= float(n)
    return time
```
Full Notebooke [here](https://github.com/HeLehm/demucs/blob/mps_speed_test/mps_speed_test.ipynb).
Here are the results:
**NOTE:** these numbers are not compatible to [my previous comment](https://github.com/facebookresearch/demucs/pull/503#issuecomment-1574858745), as I ran everything three times there and only once here.

Testing mdx with gradients
CPU time: 21.26s, MPS time: 11.79s
Speedup: 1.80x

Testing mdx without gradients
CPU time: 21.26s, MPS time: 13.40s
Speedup: 1.59x

Testing htdemucs with gradients
CPU time: 17.18s, MPS time: 6.94s
Speedup: 2.48x

Testing htdemucs without gradients
CPU time: 17.19s, MPS time: 4.23s
Speedup: 4.06x

Testing htdemucs_ft with gradients
CPU time: 68.47s, MPS time: 16.78s
Speedup: 4.08x

Testing htdemucs_ft without gradients
CPU time: 67.96s, MPS time: 16.69s
Speedup: 4.07x

Testing htdemucs_6s with gradients
CPU time: 17.09s, MPS time: 4.86s
Speedup: 3.52x

Testing htdemucs_6s without gradients
CPU time: 16.52s, MPS time: 4.28s
Speedup: 3.86x

Testing hdemucs_mmi with gradients
CPU time: 6.60s, MPS time: 5.83s
Speedup: 1.13x

Testing hdemucs_mmi without gradients
CPU time: 6.60s, MPS time: 3.85s
Speedup: 1.71x

Testing mdx_extra with gradients
CPU time: 26.35s, MPS time: 28.73s
Speedup: 0.92x

Testing mdx_extra without gradients
CPU time: 26.07s, MPS time: 22.78s
Speedup: 1.14x

As you can see, on CPU it doesn't really matter greatly if we use `torch.no_grad()` or not. I will try to do even more precise tests in the future.

It would also be helpful if someone else could run the notebook on their Apple M1/M2 device, to verify these results.

2023-06-08 23:21 UTC, CarlGao4 commented
Thanks a lot for your work!!!

What I asked and care is something like this:
```python
t1 = time.time()
...
t2 = time.time()
x.to("cpu")
...
x.to("mps")
t3 = time.time()
...
t4 = time.time()
print(t2 - t1 + t4 - t3)
```

To achieve this and pass `t2` and `t3` to your codes, I suggest that you can directly do this:
```python
# test.py
import __main__
__main__.start_time = time.time()
apply_model()
__main__.end_time = time.time()
print(__main__.end_time - __main__.start_time)
```
```python
# hdemucs.py / htdemucs.py
...
import __main__     # Use this to get the environment of your codes
st = time.time()    # before hdemucs.py#L779 and htdemucs.py#L632
x.cpu()
...
x.to("mps")
et = time.time()
__main__.start_time += et - st
```

2023-06-09 11:33 UTC, HeLehm commented
Alright, I did. Code as always [here](https://github.com/HeLehm/demucs/tree/mps_speed_test).

Here is an image of the results:
On the y axis, we have the model and if grads (False -> run with torch.no_grad()).
On the x axis, we can see the different code blocks(look at [hdemucs.py](https://github.com/HeLehm/demucs/blob/mps_speed_test/demucs/hdemucs.py) / [htdemucs.py](https://github.com/HeLehm/demucs/blob/mps_speed_test/demucs/htdemucs.py) for more info)
You can Ignore the heat map scale on the right side, as each column is normalised independently.
The values are cpu - mps time, so big negative numbers mean mps was way faster.

The raw csv data is also uploaded [here](https://github.com/HeLehm/demucs/blob/mps_speed_test/demucs_performance.csv) and [here](https://github.com/HeLehm/demucs/blob/mps_speed_test/subtracted_data.csv).

![demucs](https://github.com/facebookresearch/demucs/assets/38007156/783e3504-b571-4a68-8c07-d519e30e07fc)

2023-06-09 11:48 UTC, CarlGao4 commented
But, which operations must be done on cpu?

2023-06-09 11:51 UTC, CarlGao4 commented
What I can't understand is that why the results are different each time you test this

2023-09-04 16:01 UTC, MrSimmo commented
Wonder if anyone knows what could be wrong - I've pulled the latest versions of the demucs folder from github and overwritten my local copy.

When I use -d mps on htdemucs or htdemucs_ft models - it works fine. Quite a bit quicker than without. But when I try using it on mdx or mdx_extra, I get a bunch of silent output files.

Using Apple M1 silicon on MacOS ventura, python 3.9.6.

Does anyone know what could be the issue?

2023-10-08 22:52 UTC, genevera commented
It's still really, really slow running mdx models on mps.  I've got a M2Max with Sonoma and running HeLehm's code from the notebook gets me the following:

```bash
Testing htdemucs_6s with gradients
/Users/genevera/.pyenv/versions/miniconda3-latest/lib/python3.10/site-packages/demucs/apply.py:240: UserWarning: MPS: no support for int64 min/max ops, casting it to int32(Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/mps/operations/ReduceOps.mm:1271.)
  weight = (weight / weight.max())**transition_power
CPU time: 5.16s, MPS time: 11.04s
Speedup: 0.47x

Testing htdemucs_6s without gradients
CPU time: 5.17s, MPS time: 0.74s
Speedup: 6.98x

Testing hdemucs_mmi with gradients
CPU time: 2.37s, MPS time: 17.92s
Speedup: 0.13x

Testing hdemucs_mmi without gradients
CPU time: 2.37s, MPS time: 22.23s
Speedup: 0.11x

Testing htdemucs_ft with gradients
CPU time: 34.05s, MPS time: 6.35s
Speedup: 5.36x

Testing htdemucs_ft without gradients
CPU time: 22.01s, MPS time: 3.11s
Speedup: 7.09x

Testing htdemucs with gradients
CPU time: 5.61s, MPS time: 0.78s
Speedup: 7.15x

Testing htdemucs without gradients
CPU time: 5.65s, MPS time: 0.80s
Speedup: 7.04x

Testing repro_mdx_a with gradients
CPU time: 7.51s, MPS time: 79.45s
Speedup: 0.09x

Testing repro_mdx_a without gradients
CPU time: 7.32s, MPS time: 100.32s
Speedup: 0.07x

Testing mdx_extra_q with gradients
CPU time: 8.64s, MPS time: 65.12s
Speedup: 0.13x

Testing mdx_extra_q without gradients
CPU time: 8.87s, MPS time: 67.84s
Speedup: 0.13x

Testing mdx with gradients
CPU time: 6.65s, MPS time: 61.50s
Speedup: 0.11x

Testing mdx without gradients
CPU time: 6.93s, MPS time: 65.82s
Speedup: 0.11x

Testing repro_mdx_a_time_only with gradients
CPU time: 6.01s, MPS time: 65.09s
Speedup: 0.09x

Testing repro_mdx_a_time_only without gradients
CPU time: 5.82s, MPS time: 23.45s
Speedup: 0.25x

Testing mdx_extra with gradients
CPU time: 9.19s, MPS time: 112.45s
Speedup: 0.08x

Testing mdx_extra without gradients
CPU time: 9.43s, MPS time: 77.31s
Speedup: 0.12x

Testing repro_mdx_a_hybrid_only with gradients
CPU time: 9.16s, MPS time: 90.22s
Speedup: 0.10x

Testing repro_mdx_a_hybrid_only without gradients
CPU time: 9.03s, MPS time: 100.25s
Speedup: 0.09x

Testing mdx_q with gradients
CPU time: 7.03s, MPS time: 117.97s
Speedup: 0.06x

Testing mdx_q without gradients
CPU time: 6.82s, MPS time: 64.27s
Speedup: 0.11x
```

2024-10-01 17:22 UTC, Andy671 commented
Thanks so much for this PR. You saved us hours of processing time!